USE_CCACHE = yes

# KEY_OVERRIDE_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIA_ENABLE = yes

# CONSOLE_ENABLE = no
# EXTRAKEY_ENABLE = yes
# MIDI_ENABLE = no
# MOUSEKEY_ENABLE = no
# NKRO_ENABLE = no
# OS_DETECTION_DEBUG_ENABLE = yes
# OS_DETECTION_ENABLE = yes
# RAW_ENABLE = no
# RGB_MATRIX_ENABLE = yes
# SPLIT_KEYBOARD = no
# STENO_ENABLE = no
# UNICODE_ENABLE = yes
# VIRTSER_ENABLE = yes
