USE_CCACHE = yes

# KEY_OVERRIDE_ENABLE = yes

RGB_MATRIX_ENABLE = yes

# CONSOLE_ENABLE = yes
# COMMAND_ENABLE = yes

# MIDI_ENABLE = yes
# OS_DETECTION_DEBUG_ENABLE = yes
# OS_DETECTION_ENABLE = yes
# UNICODE_ENABLE = yes
# VIA_ENABLE = yes
# VIRTSER_ENABLE = yes

# Reduce size
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
